version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
